name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    env:
      POSTGRES_USER: postgres
      PGPASSWORD: postgres
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.7'
            django-version: '1.11.29'
          - os: ubuntu-latest
            python-version: '3.9'
            django-version: '2.2.28'
          - os: ubuntu-latest
            python-version: '3.10'
            django-version: '3.2.23'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install --upgrade pip
      - run: pip install django==${{ matrix.django-version}}
      - run: pip install psycopg2
      - run: psql -d template1 -c 'create extension cube;' -U $POSTGRES_USER -h localhost
      - run: psql -d template1 -c 'create extension earthdistance;' -U $POSTGRES_USER -h localhost
      - run: python setup.py -q install
      - run: python runtests.py
